name: uran_company_test
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0
  get_it: ^7.2.0
  hive_flutter: ^1.1.0
  path_provider: ^2.0.13
  equatable: ^2.0.5
  dio: ^5.0.3
  flutter_bloc: ^8.1.2
  cached_network_image: ^3.2.3
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/png/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/png/
